environment: 'dev'

dev:
    name: 'Pokedex'
    url: 'http://localhost:8888/'
    database:
        username: 'root'
        password: 'root'
        name: 'inventory'
        host: 'localhost'
        type: 'mysql'
    debug: true
    twig:
        cache: false
    minify:
        stylesheet: false
        javascript: false
    salt: '8dezY!2deH'

prod:
    url: 'http://localhost:8888/'
    database:
        username: 'root'
        password: 'root'
        name: 'blog'
        host: 'localhost'
        type: 'mysql'
    debug: false
    twig:
        cache: true
    minify:
        stylesheet: true
        javascript: true
